### PR TITLE
dynamic test ports

### PR DESCRIPTION
**Pull request by jbwheatley**
did try this with https://github.com/kflorence/port-manager, but parallel tests were simultaneously claiming the same port it seemed

### CODE REVIEW

**Comment by kflorence** [comment]
@jbwheatley huh, weird. since that is the whole point of that library I will need to fix it :D

**Comment by kflorence** [comment]
https://github.com/kflorence/port-manager/issues/5

**Comment by kflorence** [comment]
@jbwheatley how did you attempt to use the library? I don't see any commits here that refer to it so hard to say. It's important that you create and reference a single instance of the port manager across everything though, just in case that was the issue. I haven't been able to reproduce the problem yet but I'm trying in the above issue.

**Comment by jbwheatley** [comment]
@kflorence yeah sorry I was only playing with it locally. I   think the issue was that because each module is compiled separately, they cannot have any shared state in an object. So the port pool inevitably gets instantiated once per module.

**Pull request merged**
